name: Create ZIP Archive
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create monitor-tool folder if it doesn't exist
        run: |
          mkdir -p monitor-tool
          # Optionally add some default files
          echo "This is a placeholder file" > monitor-tool/placeholder.txt
        working-directory: ./posting_server

      - name: Debug directory contents
        run: |
          ls -R
        working-directory: ./posting_server

      - name: Create ZIP file
        run: |
          zip -r monitor-tool.zip monitor-tool
        working-directory: ./posting_server

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitor-tool
          path: posting_server/monitor-tool.zip
