name: Create ZIP Archive
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP file
        run: |
          zip -r my-folder.zip my-folder
        working-directory: ./posting_server

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitor-tool
          path: monitor-tool.zip
